# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Obsi < Formula
  desc "CLI for Obsidian note-taking with Quick Notes support"
  homepage "https://github.com/avi8or/obsidian-cli-quick-notes"
  version "0.3.7"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/avi8or/obsidian-cli-quick-notes/releases/download/v0.3.7/obsidian-cli-quick-notes_0.3.7_darwin_amd64.tar.gz"
      sha256 "f37410f3811703f6e17bc5c74aeca9744a58df9511cd4597767be13cbbe96109"

      def install
        bin.install "obsidian-cli" => "obsi"
        bin.install_symlink "obsi" => "obsidian-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/avi8or/obsidian-cli-quick-notes/releases/download/v0.3.7/obsidian-cli-quick-notes_0.3.7_darwin_arm64.tar.gz"
      sha256 "8f355bac312060cd2ed3a9a81af52316002b71908589b6ca85fae0dac7aef898"

      def install
        bin.install "obsidian-cli" => "obsi"
        bin.install_symlink "obsi" => "obsidian-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/avi8or/obsidian-cli-quick-notes/releases/download/v0.3.7/obsidian-cli-quick-notes_0.3.7_linux_amd64.tar.gz"
      sha256 "d579b9b157d1463c716f24d46534a130c4a9c07ee21a42ea360f1ab7b38436be"
      def install
        bin.install "obsidian-cli" => "obsi"
        bin.install_symlink "obsi" => "obsidian-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/avi8or/obsidian-cli-quick-notes/releases/download/v0.3.7/obsidian-cli-quick-notes_0.3.7_linux_arm64.tar.gz"
      sha256 "ee7821f815257645a729e0bcb4322fa4d8c392e94f5ac473b170c8e2b9bf53c8"
      def install
        bin.install "obsidian-cli" => "obsi"
        bin.install_symlink "obsi" => "obsidian-cli"
      end
    end
  end
end
