# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Obsi < Formula
  desc "CLI for Obsidian note-taking with Quick Notes support"
  homepage "https://github.com/avi8or/obsidian-cli-quick-notes"
  version "0.3.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/avi8or/obsidian-cli-quick-notes/releases/download/v0.3.6/obsidian-cli-quick-notes_0.3.6_darwin_amd64.tar.gz"
      sha256 "ac7b5d5f208518ed820bcea43e9166dbe7336bf815a1c0a1f1450f64c5036475"

      def install
        bin.install "obsidian-cli" => "obsi"
        bin.install_symlink "obsi" => "obsidian-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/avi8or/obsidian-cli-quick-notes/releases/download/v0.3.6/obsidian-cli-quick-notes_0.3.6_darwin_arm64.tar.gz"
      sha256 "871f374543c540f4a063041c03300bf71788144ed8e7a6742b9b3cef6a47fc22"

      def install
        bin.install "obsidian-cli" => "obsi"
        bin.install_symlink "obsi" => "obsidian-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/avi8or/obsidian-cli-quick-notes/releases/download/v0.3.6/obsidian-cli-quick-notes_0.3.6_linux_amd64.tar.gz"
      sha256 "2a016d20a1edbc28dd74fdff0b592e259ca49be0352db11263b0dc5edb4deb57"
      def install
        bin.install "obsidian-cli" => "obsi"
        bin.install_symlink "obsi" => "obsidian-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/avi8or/obsidian-cli-quick-notes/releases/download/v0.3.6/obsidian-cli-quick-notes_0.3.6_linux_arm64.tar.gz"
      sha256 "cecc3a5e0c9248f1f4f09f8ae86afcff3d91517d8909149d573ce348a645b9d0"
      def install
        bin.install "obsidian-cli" => "obsi"
        bin.install_symlink "obsi" => "obsidian-cli"
      end
    end
  end
end
